// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5IF3eFb_qb_0v-W-E299o8Z0zu_jd08',
    appId: '1:258876138596:web:370a95b545e72f78032b71',
    messagingSenderId: '258876138596',
    projectId: 'medicare-ec678',
    authDomain: 'medicare-ec678.firebaseapp.com',
    storageBucket: 'medicare-ec678.appspot.com',
    measurementId: 'G-GDNNP1DLS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLpTTgqobgFBstQeYg8r8jYhesZjiAMjQ',
    appId: '1:258876138596:android:50965e04fde0b576032b71',
    messagingSenderId: '258876138596',
    projectId: 'medicare-ec678',
    storageBucket: 'medicare-ec678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8hjBRFB6_zgxGZgXwmVUQMPSeKkDdmBk',
    appId: '1:258876138596:ios:5b0bd0c5f07bfbe1032b71',
    messagingSenderId: '258876138596',
    projectId: 'medicare-ec678',
    storageBucket: 'medicare-ec678.appspot.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8hjBRFB6_zgxGZgXwmVUQMPSeKkDdmBk',
    appId: '1:258876138596:ios:5b0bd0c5f07bfbe1032b71',
    messagingSenderId: '258876138596',
    projectId: 'medicare-ec678',
    storageBucket: 'medicare-ec678.appspot.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR5IF3eFb_qb_0v-W-E299o8Z0zu_jd08',
    appId: '1:258876138596:web:bc125601683c2e68032b71',
    messagingSenderId: '258876138596',
    projectId: 'medicare-ec678',
    authDomain: 'medicare-ec678.firebaseapp.com',
    storageBucket: 'medicare-ec678.appspot.com',
    measurementId: 'G-8ZVGCYSW2P',
  );
}
